# =====================================================
# Data displayed on the Home (About Me) page.
#
# üí° Tip for Images / Logo:
# You can use either:
# 1. A full URL (e.g., https://example.com/logo.png)
# 2. A local file placed under /public/images/ and referenced with "/" (e.g., "/images/logo.png")
# =====================================================

# =====================================================
# üë§ Personal Information
# =====================================================

profile:
  name: "Mara Popescu"
  headline: "Student @ Bocconi University"
  email: "marapopsq@gmail.com"
  location: Zurich, Switzerland

  links:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/mara-popescu1"
      icon:
        name: "FaLinkedin"
        package: "react-icons/fa6"


    - name: "R√©sum√©"
      url: "/pdf/sample-resume.pdf"
      icon:
        name: "FaRegIdBadge"
        package: "react-icons/fa6"

    - name: "Github"
      url: "https://github.com/MaraPopescu3"
      icon:
        name: "FaGithub"
        package: "react-icons/fa6"


  # you can use HTML syntax here (e.g. <br/>, <a>, <strong>, ...)
  biography: |
    Hi! I'm <strong>[Your Name]</strong>, a <em>[Your Title]</em> passionate about <em>[field or topic]</em>. Currently, I work as <em>[current role]</em> at <em>[organization]</em>, where I <em>[briefly describe your work or mission]</em>. 
    With a background in <em>[academic or professional background]</em>, I've developed strong interests in <em>[key interests or specialties]</em> and have contributed to projects like <i>[example project]</i> and <i>[another example]</i>, all focused on <em>[broader goal or impact]</em>.
    <div class="my-2"></div>
    Outside of work, I enjoy <em>[hobbies or personal interests]</em>, which inspire creativity and keep me energized. Thanks for visiting! Feel free to <a href="mailto:[your-email@example.com]" target="_blank" rel="noopener noreferrer">reach out</a> to connect.

# # =====================================================
# # üéì Education Section
# # =====================================================

education:

  - degree: "Msc. in Quantitative Finance and Risk Management"
    school: "Bocconi Univeristy"
    years: "2024 - 2025"
    logo: "/images/ntu_logo.svg"

  - degree: "Bsc. in Economics and Business Economics"
    school: "Erasmus University"
    years: "2021 - 2024"
    logo: "/images/nccu_logo.svg"

# # =====================================================
# # üíº Work Experience Section
# # =====================================================

workExperience:
  - title: "Quant Risk Modellin Intern"
    company: "UBS"
    years: "Jul. 2025 - Present"
    logo: "/images/nvidia_logo.webp"

  - title: "Analyst Intern"
    company: "Schwarz Group"
    years: "Jul 2024 - Sep 2024"
    logo: "/images/google_logo.svg"

  - title: "Teaching Assistant"
    company: "Erasmus School of Economics"
    years: "Aug. 2023 - Aug. 2024"
    logo: "/images/uiuc_logo.png"
    
# # =====================================================
# # üõ†Ô∏è Skills Section
# # =====================================================

skills:
  Programming:
    - name: "Stata"
      logo: "https://upload.wikimedia.org/wikipedia/commons/1/18/ISO_C%2B%2B_Logo.svg"
      proficiency: "[Proficiency]"
      description: "[Description]"

    - name: "Python"
      logo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg"
      proficiency: Experienced
      description: null

    - name: "Refinitiv Workspace"
      logo: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg"
      proficiency: Fluent
      description: null

  Research:
    - name: "Machine Learning"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: 2020 - Current
      description: "General machine learning methods and applied research."

    - name: "Representation Learning"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: 2024 - 2025
      description: "Learning meaningful embeddings and feature representations from data."

  Language:
    - name: "English"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Fluent
      description: "C1"

    - name: "Romanian"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Native
      description: "Native fluency."
      
   - name: "German"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Intermediate
      description: "B1"

